# Generated by Django 4.2.7 on 2023-11-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="username",
            field=models.CharField(default="", max_length=50, verbose_name="Username"),
            preserve_default=False,
        ),
    ]
