# Generated by Django 4.2.7 on 2023-12-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_is_admin_alter_account_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Address"
            ),
        ),
    ]
