# Generated by Django 4.2.7 on 2023-12-07 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="address",),
        migrations.RemoveField(model_name="account", name="fax",),
        migrations.RemoveField(model_name="account", name="nickname",),
        migrations.RemoveField(model_name="account", name="photo_url",),
        migrations.RemoveField(model_name="account", name="ssn",),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=30, verbose_name="Nickname")),
                (
                    "fax",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Fax"
                    ),
                ),
                (
                    "ssn",
                    models.CharField(
                        max_length=15, verbose_name="Social Security Number"
                    ),
                ),
                ("address", models.CharField(max_length=250, verbose_name="Address")),
                ("status", models.BooleanField(default=True)),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allowed size is 10MG",
                        null=True,
                        upload_to="users/avatars/%Y-%m-%d/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=250, verbose_name="Address")),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="State"
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Zip Code"
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allowed size is 10MG",
                        null=True,
                        upload_to="users/profiles/%Y-%m-%d/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
