# Generated by Django 4.2.7 on 2023-12-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_account_address_remove_account_fax_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Staff", new_name="StaffProfile",),
    ]
