# Generated by Django 4.2.7 on 2023-12-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="house_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="House #"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="street_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Street #"
            ),
        ),
    ]
