# Generated by Django 4.2.7 on 2023-12-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_profile_house_no_profile_street_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="license_no",
            field=models.CharField(
                default="", max_length=30, verbose_name="License No"
            ),
            preserve_default=False,
        ),
    ]
