# Generated by Django 4.2.7 on 2023-12-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_profile_user_alter_staffprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="color",
            field=models.CharField(default="#", max_length=10),
        ),
    ]
