# Generated by Django 4.2.7 on 2023-12-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_staffprofile_license_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="expiration_date",
            field=models.CharField(
                default="", max_length=20, verbose_name="Expiration Date"
            ),
            preserve_default=False,
        ),
    ]
