# Generated by Django 4.2.7 on 2023-12-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_staffprofile_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="expiration_date",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Expiration Date"
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="license_no",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="License No"
            ),
        ),
    ]
