# Generated by Django 4.2.7 on 2023-12-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_day", models.DateField(verbose_name="Booking Day")),
                ("amount", models.FloatField(default=0, verbose_name="Amount")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Upcoming", "Upcoming"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Upcoming",
                        max_length=30,
                        verbose_name="Appointment Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time", models.CharField(max_length=15, verbose_name="Time")),
            ],
            options={
                "verbose_name": "TimeSlot",
                "verbose_name_plural": "TimeSlots",
                "unique_together": {("time",)},
            },
        ),
        migrations.CreateModel(
            name="YearOfWeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_day", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "is_booking",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "time_slots",
                    models.ManyToManyField(
                        related_name="time_slots",
                        to="appointment.timeslot",
                        verbose_name="Time Slots",
                    ),
                ),
            ],
            options={
                "verbose_name": "YearOfWeekDay",
                "verbose_name_plural": "YearOfWeekDays",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointment.appointment",
                        verbose_name="Booking",
                    ),
                ),
                (
                    "packages",
                    models.ManyToManyField(
                        to="shop.service", verbose_name="Booking Service"
                    ),
                ),
            ],
            options={"verbose_name": "Booking", "verbose_name_plural": "Bookings",},
        ),
        migrations.AddField(
            model_name="appointment",
            name="booking_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.yearofweekday",
                verbose_name="Booking Time",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="profile_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="account.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="shop_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="shop.shop",
                verbose_name="Shop",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="staff_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="account.staffprofile",
                verbose_name="Staff",
            ),
        ),
    ]
