# Generated by Django 4.2.7 on 2023-12-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="booking_time",
            field=models.CharField(max_length=10, verbose_name="Booking Time"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="appointment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="appointment.appointment",
                verbose_name="Booking",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="packages",
            field=models.ManyToManyField(
                related_name="bookings",
                to="shop.service",
                verbose_name="Booking Service",
            ),
        ),
    ]
