# Generated by Django 4.2.7 on 2023-12-25 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_profile_house_no_profile_street_no"),
        ("appointment", "0005_review"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="email",),
        migrations.RemoveField(model_name="review", name="full_name",),
        migrations.RemoveField(model_name="review", name="phone",),
        migrations.AddField(
            model_name="review",
            name="profile_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="account.profile",
                verbose_name="Profile",
            ),
            preserve_default=False,
        ),
    ]
