# Generated by Django 4.2.7 on 2023-12-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform_name",
                    models.CharField(
                        choices=[
                            ("All", "All"),
                            ("Web", "Web"),
                            ("iOS", "iOS"),
                            ("Android", "Android"),
                        ],
                        default="All",
                        max_length=15,
                        verbose_name="Platform Name",
                    ),
                ),
                ("ip", models.CharField(max_length=20, verbose_name="IP Address")),
                ("device", models.CharField(max_length=100, verbose_name="Device")),
                ("uuid", models.CharField(max_length=250, verbose_name="UUID")),
            ],
            options={"verbose_name": "Platform", "verbose_name_plural": "Platforms",},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "price",
                    models.FloatField(blank=True, null=True, verbose_name="Price"),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Symbol"
                    ),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allows size is 20MB",
                        null=True,
                        upload_to="services/%Y-%m-%d/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="Shop Name"),
                ),
                ("tel", models.CharField(max_length=20, verbose_name="Tel")),
                ("fax", models.CharField(max_length=20, verbose_name="Fax")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Website"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Twitter"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Instagram"
                    ),
                ),
                ("address", models.CharField(max_length=250, verbose_name="Address")),
                ("latitude", models.FloatField(default=0, verbose_name="Latitude")),
                ("longitude", models.FloatField(default=0, verbose_name="Longitude")),
                (
                    "banner_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allow size is 10MB",
                        null=True,
                        upload_to="shops/shops/banners/%Y-%m-%d/",
                        verbose_name="Banner URL",
                    ),
                ),
                (
                    "logo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allow size is 5MB",
                        null=True,
                        upload_to="shops/shops/logos/%Y-%m-%d/",
                        verbose_name="Logo URL",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="About"),
                ),
                (
                    "services",
                    models.ManyToManyField(to="shop.service", verbose_name="Service"),
                ),
                (
                    "staffs",
                    models.ManyToManyField(
                        to="account.staffprofile", verbose_name="Staff"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
                "unique_together": {("shop_name", "tel", "email", "address")},
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("subtitle", models.CharField(max_length=250, verbose_name="SubTitle")),
                ("discount", models.FloatField(verbose_name="Discount")),
                (
                    "color",
                    models.CharField(
                        default="#",
                        help_text="Hex Color [Ex: #C3C3C3]",
                        max_length=10,
                        verbose_name="Color",
                    ),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allow size is 10MB",
                        null=True,
                        upload_to="shops/promotions/%Y-%m-%d/",
                        verbose_name="Photo URL",
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.service",
                        verbose_name="Service",
                    ),
                ),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="shop.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={"verbose_name": "Promotion", "verbose_name_plural": "Promotions",},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "subtitle",
                    models.CharField(max_length=250, verbose_name="Sub Title"),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allowed size is 20MB",
                        null=True,
                        upload_to="shops/notifications/%Y-%m-%d/",
                        verbose_name="Photo URL",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "platform_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.platform",
                        verbose_name="Platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo_url",
                    models.ImageField(
                        blank=True,
                        help_text="Allow size is 20MB",
                        null=True,
                        upload_to="shops/shops/galleries/%Y-%m-%d/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to="shop.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={"verbose_name": "Gallery", "verbose_name_plural": "Galleries",},
        ),
        migrations.CreateModel(
            name="BusinessHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.CharField(max_length=25, verbose_name="Day")),
                ("hour", models.CharField(max_length=25, verbose_name="Hour")),
                (
                    "shop_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_hours",
                        to="shop.shop",
                        verbose_name="Shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "BusinessHour",
                "verbose_name_plural": "BusinessHours",
            },
        ),
    ]
