# Generated by Django 4.2.7 on 2023-11-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_service_description_service_price_service_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
            preserve_default=False,
        ),
    ]
