# Generated by Django 4.2.7 on 2023-12-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="shop_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to="shop.shop",
                verbose_name="Shop",
            ),
        ),
    ]
