# Generated by Django 4.2.7 on 2023-12-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_shop_services_alter_businesshour_shop_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesshour",
            name="shop_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_hours",
                to="shop.shop",
                verbose_name="Shop",
            ),
        ),
    ]
