# Generated by Django 4.2.7 on 2023-12-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_businesshour_shop_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="promotion", name="description",),
        migrations.AddField(
            model_name="promotion",
            name="discount",
            field=models.FloatField(default=0, verbose_name="Discount"),
            preserve_default=False,
        ),
    ]
