# Generated by Django 4.2.7 on 2023-12-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_promotion_description_promotion_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="isSelected",
            field=models.BooleanField(default=False),
        ),
    ]
