# Generated by Django 4.2.7 on 2023-12-15 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0011_alter_shop_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="users",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
    ]
